refactor: *

diff --git a/lemon b/lemon
--- a/lemon
+++ b/lemon
@@ -1,3 +1,30 @@
 #!/bin/bash
 
+if [ ! -f "./Cargo.toml" ]; then
+  echo "you can't run lemon outside of lemon directory"
+  exit 1
+fi
+
+
+if [ "$1" = "build" ] || [ "$1" = "-b" ]; then
+  cargo build --release
+  exit 0
+fi
+
+if [ ! -f "./target/release/lemon" ]; then
+  echo "lemon bin not found, build..."
+  cargo build --release
+fi
+
+
+# if [[ $(git status --porcelain) ]]; then
+#   echo "build with changes..."
+#    cargo build --release
+# fi
+
+if [ ! -f "./target/release/lemon" ]; then
+  echo "build failed"
+  exit 1
+fi
+
 ./target/release/lemon "$@"
